name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore "./github actions telegram bot/github actions telegram bot.csproj"
    - name: Build
      run: dotnet build --no-restore  "./github actions telegram bot/github actions telegram bot.csproj"
    - name: Run
      run: dotnet run  "./github actions telegram bot/github actions telegram bot.csproj"
    - name: cmd
      run: ls
