# This is a basic workflow to help you get started with Actions

name: TEST

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
#         run: |
#           New-Item -Path .\sjghfd.txt -ItemType File
#           ls
#           git config --global user.email "ckencodes104@gmail.com"
#           git config --global user.name "rokura104"
#           git remote set-url origin https://rokura104:${{ secrets.GITHUB_TOKEN }}@github.com/rokura104/localserver
#           git add -f ./sjghfd.txt
#           git commit -m "funn"
#           git push origin refs/heads/main:refs/tags/v1.2
        run: ls "github actions telegram bot"
